name: currency_converter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  http:
  shared_preferences: ^2.0.15
  connectivity_plus: ^6.0.3
  intl: ^0.19.0
  shimmer: ^3.0.0
  flutter_spinkit: ^5.0.0
  flutter_screenutil: ^5.9.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  get_it: ^7.6.7
  cached_network_image: ^3.3.1
  go_router: ^14.2.0
  flutter_animate: ^4.5.0
  country_currency_pickers: ^3.0.0
  flutter_slidable: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/
    - lib/assets/images/
    - lib/assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/Montserrat-Black.ttf
        - asset: lib/assets/fonts/Montserrat-Bold.ttf
        - asset: lib/assets/fonts/Montserrat-SemiBold.ttf
        - asset: lib/assets/fonts/Montserrat-Medium.ttf
        - asset: lib/assets/fonts/Montserrat-Regular.ttf
    - family: Abys
      fonts:
        - asset: lib/assets/fonts/Abys-Regular.otf
    - family: Blackness
      fonts:
        - asset: lib/assets/fonts/Blackness.ttf
  